---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: configserver
  name: configserver
  namespace: twinkle
spec:
  ports:
  - name: server-port
    port: 8888
    targetPort: 8888
  selector:
    app.kubernetes.io/name: configserver
    app.kubernetes.io/part-of: twinklecloud
  type: ClusterIP
