---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: configserver
    app.kubernetes.io/part-of: twinklecloud
  name: configserver
  namespace: twinkle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: configserver
      app.kubernetes.io/part-of: twinklecloud
  template:
    metadata:
      name: configserver
      labels:
        app.kubernetes.io/name: configserver
        app.kubernetes.io/part-of: twinklecloud
    spec:
      containers:
      - name: configserver
        image: hub.twinkle.net:8443/twinklecloud/twinkle-config-server:latest
        ports:
        - name: server-port
          containerPort: 8888
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: cloud
      imagePullSecrets:
      - name: twinkle-sec
      dnsPolicy: ClusterFirstWithHostNet