---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: discovery
  name: discovery
  namespace: twinkle
spec:
  ports:
  - name: server-port
    port: 8761
    targetPort: 8761
    nodePort: 30071
  selector:
    app.kubernetes.io/name: discovery
    app.kubernetes.io/part-of: twinklecloud
  type: NodePort
