---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: gateway
  name: gateway
  namespace: twinkle
spec:
  ports:
  - name: server-port
    port: 10000
    targetPort: 10000
    nodePort: 32072
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: twinklecloud
  type: NodePort
#  type: ClusterIP
