#  annotations:
#    volume.beta.kubernetes.io/storage-class: "slow"
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elpv01
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /esk_data/es_data
    server: 192.168.0.121
    