---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: auth-server
  name: auth-server
  namespace: twinkle
spec:
  ports:
  - name: server-port
    port: 10001
    targetPort: 8000
    nodePort: 30075
  selector:
    app.kubernetes.io/name: authorization
    app.kubernetes.io/part-of: twinklecloud
  type: NodePort