---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gluster-storage
  labels:
    glusterfs: gs-sc
    gluster-s3: sc
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.244.24.213:8080"
  restuser: "admin"
  secretNamespace: "glusterfs"
  secretName: "heketi-glusterfs-admin-secret"
  volumetype: replicate:2
